"""Precomputed continuous vortex samples; no image or trajectory work at runtime.

Generated by scripts/generate_empty_vortex.py from canonical V2C-A Braille dots.
The user's neuro_vortex.py supplies the motion reference, not a terminal driver.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from itertools import accumulate
from pathlib import Path
from types import MappingProxyType
from typing import TypedDict, cast


class _VortexData(TypedDict):
    fps: int
    duration_ms: int
    durations: list[int]
    sizes: dict[str, list[tuple[list[str], list[str]]]]


@dataclass(frozen=True, slots=True)
class RevealFrame:
    duration_ms: int
    rows: Mapping[str, tuple[str, ...]]
    levels: Mapping[str, tuple[str, ...]]


_data = cast(
    _VortexData,
    json.loads(Path(__file__).with_name("empty_state_vortex.json").read_text(encoding="utf-8")),
)
FRAME_RATE = _data["fps"]
TOTAL_DURATION_MS = _data["duration_ms"]
VORTEX_FRAMES = tuple(
    RevealFrame(
        duration,
        MappingProxyType(
            {size: tuple(frames[index][0]) for size, frames in _data["sizes"].items()}
        ),
        MappingProxyType(
            {size: tuple(frames[index][1]) for size, frames in _data["sizes"].items()}
        ),
    )
    for index, duration in enumerate(_data["durations"])
)
FRAME_DEADLINES = tuple(accumulate(frame.duration_ms for frame in VORTEX_FRAMES))
del _data
