# ruff: noqa: RUF001
from __future__ import annotations

from collections.abc import Mapping
from typing import Final

from neuro_code.shared.ui_language import UiLanguage

# Natural Chinese interface copy deliberately uses full-width punctuation.

_ENGLISH: Final[dict[str, str]] = {
    "subtitle": "Terminal coding agent",
    "prompt.placeholder": "Ask Neuro Code... (/help for commands)",
    "shortcuts": "^C Cancel  ^Q Quit  F8 Copy  Shift+Tab Mode  ^P Model  ^E Effort  ^R Sessions  ^, Settings  ^L Clear",
    "runtime.help": "F1 help",
    "transcript_copy.title": "Copy transcript",
    "transcript_copy.help": "Drag or use Shift+Arrow to select; Ctrl+A selects all; Ctrl+C copies; Esc closes.",
    "transcript_copy.select_first": "Select transcript text before copying.",
    "transcript_copy.copied": "Copied {characters} characters.",
    "transcript_copy.clipboard_unavailable": "System clipboard support is unavailable. Sent a copy request to the terminal, which may not support it.",
    "transcript_copy.empty": "The transcript is empty.",
    "assistant.copy_hint": "Double-click a reply to select and copy it.",
    "label.error": "Error",
    "label.status": "Status",
    "label.tool": "Tool",
    "approval.title": "Tool approval required",
    "approval.tool": "Tool: {tool}",
    "approval.policy": "Policy: {policy}",
    "approval.allow_once": "Allow once [A]",
    "approval.allow_session": "Allow identical action this session [S]",
    "approval.scope.heading": "Additional scoped approvals (safe candidates only):",
    "approval.scope.workspace_edits": "Allow workspace edits in {root}",
    "approval.scope.command_family": "Allow {family} commands in {root}",
    "approval.unscoped": "Session approval is unavailable for an action that cannot be scoped safely.",
    "approval.deny": "Deny [D/Esc/Ctrl+C]",
    "provider.title": "Select provider profile",
    "provider.help": "Switching profile starts a new conversation. Esc/Ctrl+C closes this picker.",
    "marker.current": "current",
    "marker.default": "default",
    "marker.unavailable": "unavailable",
    "marker.credential_missing": "credential missing",
    "session.search": "Session search: {query}",
    "session.title": "Workspace sessions",
    "session.search_placeholder": "Type to filter sessions…",
    "session.help": "Only sessions from this workspace are listed. Filter with /sessions QUERY. Esc/Ctrl+C closes this picker.",
    "session.resume_via": "resume via {profile}",
    "session.legacy_sandbox": "legacy sandbox",
    "session.sandbox": "sandbox {profile}",
    "session.sandbox_off": "sandbox off · no OS isolation",
    "session.restart_required": "restart required",
    "terminal.title": "Attached terminals",
    "terminal.none": "No attached terminals",
    "terminal.session": "{marker}{terminal_id} · pid {pid} · {status}",
    "terminal.running": "running",
    "terminal.exited": "exited ({code})",
    "terminal.status_unknown": "status unavailable",
    "terminal.output_empty": "No output yet.",
    "terminal.output_dropped": "{bytes} terminal output bytes dropped.",
    "terminal.help": "Ctrl+Shift+T focus · Ctrl+] / Ctrl+[ select · Ctrl+Shift+R resize · Ctrl+Shift+X stop · Esc chat",
    "terminal.input_placeholder": "Type input for the selected terminal…",
    "terminal.unavailable": "Attached terminals are unavailable for this binding.",
    "terminal.input_too_large": "Terminal input is too large.",
    "terminal.input_failed": "Terminal input failed: {error}",
    "terminal.stop_failed": "Terminal stop failed: {error}",
    "terminal.stopped": "Attached terminal {terminal_id} stopped.",
    "terminal.resize_failed": "Terminal resize failed: {error}",
    "terminal.resized": "Attached terminal resized to {columns}×{rows}.",
    "settings.title": "Settings",
    "settings.description": "Choose a settings category. Open a category to edit its details.",
    "settings.category.language": "Interface language  ·  {current}",
    "settings.category.providers": "Model providers  ·  profiles, protocols, endpoints, and API keys",
    "settings.category.network": "Network and proxy  ·  default connection policy",
    "settings.category.background_wake": "Background task wake  ·  global default and provider overrides",
    "settings.category.language.label": "Interface language",
    "settings.category.agent_reasoning.label": "Agent / Reasoning",
    "settings.category.agent_reasoning.value": "{effort}",
    "settings.category.agent_interaction_mode.label": "Agent / Interaction mode",
    "settings.category.agent_interaction_mode.value": "{mode}",
    "settings.category.providers.label": "Model providers",
    "settings.category.network.label": "Network and proxy",
    "settings.category.background_wake.label": "Background task wake",
    "settings.category.providers.value": "Manage",
    "settings.category.network.value": "Configure",
    "settings.category.background_wake.value": "Configure",
    "settings.current": "current",
    "settings.help": "Esc/Ctrl+C closes Settings.",
    "settings.language.title": "Interface language",
    "settings.language.description": "Choose the language used throughout the TUI.",
    "settings.language.help": "The choice applies immediately and is saved for future launches.",
    "settings.back": "Back",
    "provider_settings.first_run_title": "Set up Neuro Code",
    "provider_settings.title": "Model providers",
    "provider_settings.description": "Choose a saved profile to edit, or create another one. API keys are stored separately from normal configuration and are never shown here.",
    "provider_settings.empty": "No managed provider profiles have been saved yet.",
    "provider_settings.preset.openai": "OpenAI Responses",
    "provider_settings.preset.compatible": "Compatible Chat",
    "provider_settings.preset.deepseek": "DeepSeek",
    "provider_settings.preset.anthropic": "Anthropic",
    "provider_settings.preset.gemini": "Gemini",
    "provider_settings.preset.xai": "xAI",
    "provider_settings.preset.kimi": "Kimi",
    "provider_settings.preset.glm": "GLM",
    "provider_settings.preset.minimax": "MiniMax",
    "provider_settings.preset.ark": "Volcengine Ark",
    "provider_settings.preset.qianfan": "Baidu Qianfan",
    "provider_settings.preset.bailian": "Alibaba Model Studio",
    "provider_settings.preset.tokenhub": "Tencent TokenHub",
    "provider_settings.name": "Profile name (letters, numbers, '.', '_' or '-')",
    "provider_settings.field.name": "Provider profile",
    "provider_settings.field.model": "Model",
    "provider_settings.field.base_url": "API endpoint",
    "provider_settings.field.api_key": "Authentication",
    "provider_settings.field.context_window": "Context window",
    "provider_settings.endpoint.title": "Endpoint / region variant",
    "provider_settings.protocol.title": "Protocol for this model",
    "provider_settings.protocol.option.recommended": "Auto / Recommended",
    "provider_settings.protocol.option.chat": "OpenAI Chat",
    "provider_settings.protocol.option.responses": "OpenAI Responses",
    "provider_settings.protocol.option.anthropic": "Anthropic Messages",
    "provider_settings.protocol.option.gemini": "Gemini generateContent",
    "provider_settings.protocol.option.gemini_interactions": "Gemini Interactions",
    "provider_settings.protocol.unknown": "Model-specific protocol support is not confirmed; continue only with documented/manual evidence.",
    "provider_settings.model": "Model identifier",
    "provider_settings.model.openai": "Model identifier (for example, gpt-5.4)",
    "provider_settings.model.compatible": "Chat Completions model identifier",
    "provider_settings.model.deepseek": "deepseek-v4-pro or deepseek-v4-flash",
    "provider_settings.model.anthropic": "Anthropic model identifier",
    "provider_settings.model.gemini": "Gemini model identifier",
    "provider_settings.model.xai": "xAI model identifier",
    "provider_settings.model.kimi": "Kimi model identifier (for example, kimi-k3 or kimi-k2.6)",
    "provider_settings.model.glm": "GLM model identifier (for example, glm-5.3)",
    "provider_settings.model.minimax": "MiniMax model identifier (for example, MiniMax-M3)",
    "provider_settings.model.ark": "Ark model or endpoint model identifier",
    "provider_settings.model.qianfan": "Qianfan model identifier",
    "provider_settings.model.bailian": "Model Studio model identifier",
    "provider_settings.model.tokenhub": "TokenHub model or service identifier",
    "provider_settings.protocol.openai": "OpenAI Responses API · sends requests to /responses.",
    "provider_settings.protocol.compatible": "OpenAI-compatible Chat Completions · sends requests to /chat/completions.",
    "provider_settings.protocol.deepseek": "DeepSeek OpenAI-compatible Chat Completions · sends requests to /chat/completions; use https://api.deepseek.com with a current DeepSeek model identifier.",
    "provider_settings.protocol.anthropic": "Anthropic Messages API · sends requests to /v1/messages.",
    "provider_settings.protocol.gemini": "Gemini generateContent API.",
    "provider_settings.protocol.xai": "xAI Responses API using the xAI dialect.",
    "provider_settings.protocol.kimi": "Kimi OpenAI-compatible Chat Completions · current models are discovered from /v1/models.",
    "provider_settings.protocol.glm": "GLM OpenAI-compatible Chat Completions · the official static model list is used because no stable model-list endpoint is assumed.",
    "provider_settings.protocol.minimax": "MiniMax OpenAI-compatible Chat Completions · current models are discovered from /v1/models.",
    "provider_settings.protocol.ark": "Ark inference service · choose the documented Chat or Responses wire protocol; built-in web tools are intentionally not enabled.",
    "provider_settings.protocol.ark.chat": "Ark OpenAI-compatible Chat Completions · requests use the selected Ark endpoint.",
    "provider_settings.protocol.ark.responses": "Ark Responses API · portable function calling is enabled through the shared Responses adapter; hosted tools remain disabled.",
    "provider_settings.protocol.qianfan": "Qianfan inference service · protocol support is checked against the selected model evidence.",
    "provider_settings.protocol.qianfan.chat": "Qianfan OpenAI-compatible Chat Completions.",
    "provider_settings.protocol.qianfan.responses": "Qianfan OpenAI-compatible Responses · only documented model entries are marked supported.",
    "provider_settings.protocol.qianfan.anthropic": "Qianfan Anthropic-compatible Messages · wire compatibility only; Anthropic server tools are not inherited.",
    "provider_settings.protocol.bailian": "Alibaba Model Studio · endpoint and billing-plan scope are part of this profile identity.",
    "provider_settings.protocol.bailian.chat": "Model Studio OpenAI-compatible Chat Completions.",
    "provider_settings.protocol.bailian.responses": "Model Studio OpenAI-compatible Responses · portable Responses only; hosted tools remain disabled.",
    "provider_settings.protocol.bailian.anthropic": "Model Studio Anthropic-compatible Messages · this endpoint does not provide /v1/models discovery.",
    "provider_settings.protocol.tokenhub": "TokenHub · the selected model controls whether Responses is native, converted, or unsupported.",
    "provider_settings.protocol.tokenhub.chat": "TokenHub OpenAI-compatible Chat Completions.",
    "provider_settings.protocol.tokenhub.responses": "TokenHub OpenAI Responses · model evidence distinguishes native and compatibility-converted support.",
    "provider_settings.protocol.tokenhub.anthropic": "TokenHub Anthropic-compatible Messages · auth is delegated to the shared Anthropic adapter.",
    "provider_settings.base_url": "API base URL",
    "provider_settings.api_key": "API key (leave blank to keep the saved key)",
    "provider_settings.api_key_required": "An API key is required for a new profile.",
    "provider_settings.context_window": "Context capacity in tokens (for example 128000)",
    "provider_settings.context_window_hint": "Optional, but required for an accurate runtime context percentage. This capability value is local metadata and is never sent to the provider.",
    "provider_settings.context_window_invalid": "Context capacity must be a positive whole number.",
    "provider_settings.connection.test": "Test and load models",
    "provider_settings.connection.testing": "Testing connection…",
    "provider_settings.connection.success": "Connection succeeded. Loaded {count} models; choose one below or enter an identifier manually.",
    "provider_settings.connection.success_empty": "Connection succeeded, but the provider returned no selectable models. Enter the model identifier manually.",
    "provider_settings.connection.success_selected": "Connection succeeded. Loaded {count} models and confirmed {model!r} is available.",
    "provider_settings.connection.success_missing": "Connection succeeded and loaded {count} models, but {model!r} was not listed. Choose a model below or keep the manual identifier if the provider supports hidden models.",
    "provider_settings.connection.selected": "Selected model {model!r}. Save the profile to use it.",
    "provider_settings.connection.stale": "The draft changed while the connection test was running. Discarded the old result; test again when ready.",
    "provider_settings.connection.static": "Showing the bounded official model list. Credentials were not tested; manual model entry remains available.",
    "provider_settings.connection.manual_only": "This protocol has no safe inference model-list endpoint. Enter a documented model identifier manually; no credential request was made.",
    "provider_settings.connection.fallback": "Model discovery was unavailable. Showing a bounded official fallback list; credentials were not validated and manual model entry remains available.",
    "provider_settings.connection.truncated": " The bounded list shows only the first 200 identifiers.",
    "provider_settings.connection.error.authentication": "Authentication failed (HTTP {status}). Check the API key and account access.",
    "provider_settings.connection.error.endpoint": "The model catalog endpoint was not found (HTTP {status}). Check the base URL and selected API protocol; manual model entry remains available for compatible servers without a catalog.",
    "provider_settings.connection.error.timeout": "The provider connection timed out. Check the network, proxy, and endpoint.",
    "provider_settings.connection.error.rate_limit": "The provider rate-limited the connection test (HTTP {status}). Try again later.",
    "provider_settings.connection.error.server": "The provider returned a server error (HTTP {status}). Try again later.",
    "provider_settings.connection.error.http": "The provider rejected the model catalog request (HTTP {status}). Check the endpoint and account permissions.",
    "provider_settings.connection.error.proxy": "The proxy connection failed: {detail}",
    "provider_settings.connection.error.network": "The provider could not be reached: {detail}",
    "provider_settings.connection.error.response_too_large": "The provider model catalog exceeded the safe one-megabyte response limit.",
    "provider_settings.connection.error.invalid_response": "The provider returned an invalid model catalog response. Check that the base URL matches the selected protocol.",
    "provider_settings.connection.error.unknown": "The provider connection test failed: {detail}",
    "provider_settings.proxy.title": "Provider proxy override",
    "provider_settings.proxy.inherit": "Use global default",
    "provider_settings.proxy.environment": "Use environment",
    "provider_settings.proxy.direct": "Direct",
    "provider_settings.proxy.explicit": "Named variable",
    "provider_settings.proxy.environment_variable": "Proxy URL environment variable (for example NEURO_DEEPSEEK_PROXY_URL)",
    "provider_settings.proxy.hint.environment": "Uses and validates HTTP_PROXY, HTTPS_PROXY, ALL_PROXY, NO_PROXY, and certificate environment settings before saving.",
    "provider_settings.proxy.hint.direct": "Ignores proxy and certificate environment settings for this provider.",
    "provider_settings.proxy.hint.explicit": "Reads one proxy URL from the named environment variable. The URL and credentials are never saved or displayed.",
    "provider_settings.proxy.hint.inherit": "Uses the global default policy: {policy}. Choose an override only when this provider needs a different route.",
    "provider_settings.background_wake.title": "Background-task wake override",
    "provider_settings.background_wake.inherit": "Use global default",
    "provider_settings.background_wake.disabled": "Disabled",
    "provider_settings.background_wake.enabled": "Enabled",
    "provider_settings.background_wake.hint": "This profile override applies when the provider is selected; otherwise the global default is used.",
    "network_settings.title": "Network and proxy",
    "network_settings.description": "Choose the default network route for managed providers. A provider may explicitly override this policy without storing a proxy URL.",
    "network_settings.default_policy": "Global default policy",
    "network_settings.environment": "Use environment",
    "network_settings.direct": "Direct",
    "network_settings.explicit": "Named variable",
    "network_settings.environment_variable": "Proxy URL environment variable (for example NEURO_CODE_PROXY_URL)",
    "network_settings.hint.environment": "Uses and validates HTTP_PROXY, HTTPS_PROXY, ALL_PROXY, NO_PROXY, and certificate environment settings before saving.",
    "network_settings.hint.direct": "Ignores proxy and certificate environment settings by default. Providers may still opt into a different route.",
    "network_settings.hint.explicit": "Reads one proxy URL from the named environment variable. The URL and credentials are never saved or displayed.",
    "network_settings.policy.environment": "environment settings",
    "network_settings.policy.direct": "direct connection",
    "network_settings.policy.explicit": "named proxy variable",
    "network_settings.save": "Save network default",
    "background_wake_settings.title": "Background task wake",
    "background_wake_settings.description": "Choose the global default for idle sessions. A provider profile may override it.",
    "background_wake_settings.default_policy": "Global default policy",
    "background_wake_settings.disabled": "Disabled",
    "background_wake_settings.enabled": "Enabled",
    "background_wake_settings.hint.disabled": "Completed background tasks are announced, but never start an autonomous model turn by default.",
    "background_wake_settings.hint.enabled": "An idle TUI may start at most one bounded model-only wake for each pending completion batch.",
    "background_wake_settings.save": "Save wake default",
    "provider_settings.new": "New profile",
    "provider_settings.delete": "Delete profile",
    "provider_settings.delete_confirm": "Confirm delete",
    "provider_settings.delete_warning": "Delete {profile!r} and its stored API key? Press Confirm delete to continue.",
    "provider_settings.save_use": "Save and use",
    "effort.title": "Reasoning effort",
    "effort.description.low": "Fast",
    "effort.description.medium": "Balanced",
    "effort.description.high": "Deep",
    "effort.description.xhigh": "Complex tasks",
    "effort.description.max": "Maximum single-agent depth",
    "effort.description.ultracode": "Automatic bounded delegation",
    "effort.workflow_delegation": "bounded path",
    "effort.help": "Applies from the next model step. Ultracode selects MAIN_MAX or the existing bounded Agent Swarm.",
    "interaction_mode.title": "Interaction mode",
    "interaction_mode.description.normal": "Read-only exploration; effects still need approval.",
    "interaction_mode.description.accept-edits": "Workspace edits may proceed; other effects remain approval-gated.",
    "interaction_mode.description.plan": "Explore and prepare a plan without side effects.",
    "interaction_mode.description.auto": "Continue through safe work within every explicit boundary.",
    "interaction_mode.help": "Applies from the next model step. Shift+Tab and /mode use this same preference.",
    "runtime.model": "MODEL",
    "runtime.context": "CTX",
    "runtime.context_unknown": "?",
    "runtime.context_help_unknown": "The provider context window is not configured, so a percentage cannot be calculated.",
    "runtime.context_help_estimated": "Estimated conversation context: approximately {used} / {window} tokens. Provider-reported usage replaces this estimate after a model step.",
    "runtime.context_help_preflight": "Estimated request pressure, including output reserve and safety margin: approximately {used} / {window} tokens.",
    "runtime.context_help_reported": "Conversation context after the latest model step: {used} / {window} provider-reported tokens.",
    "runtime.effort": "EFFORT",
    "runtime.effort_help": "Application review policy. Ultracode selects one durable MAIN_MAX or bounded Agent Swarm path; MAX remains ordinary single-agent depth.",
    "runtime.ultracode": "UltraCode",
    "runtime.ultracode.auto_routing": "Auto",
    "runtime.ultracode.auto_routing_detail": "Auto Routing",
    "runtime.ultracode.main_max": "MAIN_MAX",
    "runtime.ultracode.swarm": "Swarm",
    "runtime.ultracode.provider_effort": "Provider {effort}",
    "runtime.workspace": "CWD",
    "runtime.mode": "MODE",
    "runtime.mode_help.normal": "Normal: read-only tools run automatically; edits and commands require approval.",
    "runtime.mode_help.accept-edits": "Accept Edits: reads and workspace edits run automatically; commands and other effects still require approval.",
    "runtime.mode_help.plan": "Plan: only read-only exploration is allowed; side-effecting requests are denied.",
    "runtime.mode_help.auto": "Auto (limited): reads and edits run automatically; commands and network effects still require approval until a safety classifier is implemented.",
    "runtime.mode_help_auto_unrestricted": "Auto was explicitly authorized by --always-approve. Explicit deny rules and the configured process sandbox still apply; no safety classifier is active yet.",
    "startup.resumed": "Resumed session {session_id} · {provider}/{model} · {cwd}",
    "startup.ready": "Ready · {provider}/{model} · {cwd}",
    "session.stuck_recoverable": "The previous turn entered a repeated loop and was stopped safely. You can continue with a new instruction.",
    "session.budget_limited_recoverable": "The previous turn reached its execution budget and was stopped safely. You can continue with a new instruction.",
    "session.recovery.safe": "Interrupted turn {turn_id} is safely retryable before model output. Use /recover retry {turn_id} or /recover abandon {turn_id}.",
    "session.recovery.retry_unavailable": "Interrupted plan turn {turn_id} is safely held, but plan retry is unavailable. Use /recover abandon {turn_id}.",
    "session.recovery.indeterminate": "Interrupted turn {turn_id} is indeterminate after {stage}. Do not replay it; use /recover abandon {turn_id} before continuing.",
    "session.recovery.abandoned": "Interrupted turn {turn_id} was explicitly abandoned.",
    "recovery.unavailable": "Crash recovery controls are unavailable in this session.",
    "recovery.usage": "Usage: /recover [inspect|abandon TURN_ID|retry TURN_ID].",
    "recovery.none": "No interrupted turn attempts found.",
    "recovery.item": "{turn_id} · {status} · stage={stage} · input={input_state} · retry={retry_available} · abandon={abandon_available} · {reason}",
    "turn.running": "A turn is already running.",
    "turn.interjection_queued": "Queued until the current response completes.",
    "turn.interjection_restored": "Queued prompt restored to the input.",
    "turn.interjections_restored": "{count} queued prompt(s) were restored to the draft and will not be sent automatically.",
    "turn.interjection_limit": "Too many queued prompts; wait for the current turn to finish.",
    "turn.waiting": "Thinking...",
    "turn.finalizing": "Safely finalizing...",
    "turn.activity.thinking": "Working",
    "turn.activity.model": "Waiting for the model",
    "turn.activity.reasoning": "Reasoning",
    "turn.activity.responding": "Generating the response",
    "turn.activity.continuing": "Continuing the task",
    "turn.activity.waiting_input": "Waiting for your input",
    "turn.activity.finalizing": "Safely finalizing",
    "turn.activity.orchestrating": "Orchestrating",
    "turn.activity.completed": "Completing the turn",
    "turn.activity.failed": "Stopping the turn",
    "turn.activity.running_tool": "Running {tool}",
    "turn.activity.waiting_tool": "Waiting in {tool}",
    "turn.provider_balance_recoverable": "The model provider declined this request because the account balance is insufficient. This session is still open; add credit or switch provider, then send a new instruction.",
    "turn.provider_failure_recoverable": "The model provider request failed. This session is still open; check provider settings or switch provider, then try again.",
    "turn.stuck_recoverable": "The task entered a repeated loop and was stopped safely. You can continue with a new instruction.",
    "turn.budget_limited_recoverable": "This turn reached its execution budget and was stopped safely. You can continue with a new instruction.",
    "turn.no_response": "(no text response)",
    "turn.cancelled": "Turn cancelled.",
    "turn.reasoning": "Reasoning...",
    "turn.thinking_completed": "Reasoning finished · {duration} · model step {step}",
    "turn.completed": "Turn completed in {duration} · {steps} model step(s)",
    "turn.cancel_requested": "Cancellation requested.",
    "interaction.submitted": "Answer submitted; continuing the task.",
    "turn.draft_cleared": "Draft cleared.",
    "turn.draft_restored": "The cancelled prompt was restored to the draft.",
    "turn.draft_preserved": "The cancelled prompt remains above because a newer draft is already in the input.",
    "turn.none_running": "No turn is running.",
    "subagent.usage": "/subagent requires a prompt.",
    "subagent.unavailable": "The read-only subagent is unavailable in this session.",
    "subagent.session_required": "Start or resume a session before running a subagent.",
    "subagent.started": "Read-only subagent started.",
    "subagent.completed": "Read-only subagent completed · {steps} step(s).",
    "subagent.finished": "Read-only subagent finished with status {status} · {steps} step(s).",
    "subagent.truncated": "Read-only subagent response was bounded for display.",
    "subagent.cancelled": "Read-only subagent cancelled.",
    "subagent.failed": "Read-only subagent failed: {error}",
    "subagents.unavailable": "Subagent relationship visibility is unavailable in this session.",
    "subagents.session_required": "Start or resume a session before listing subagents.",
    "subagents.none": "No child subagent relationships for the current session.",
    "subagents.heading": "Child subagent relationships (read-only):\n{lines}",
    "subagents.summary": "{task_id} → {child_session_id} · {provider}/{model} · {status} · created {created} · updated {updated} · actions: {actions}",
    "subagents.actions.none": "none",
    "provider.failed": "Provider {provider} failed before output: {message}",
    "provider.selected": "Provider {provider}/{model} selected.",
    "provider.fallback_selected": "Provider {provider}/{model} fallback selected.",
    "tool.hosted_started": "● Hosted {name}",
    "tool.hosted_completed": "└ Completed {name} in {duration}",
    "tool.requested": "● {invocation}",
    "tool.permission_allowed": "├ Allowed · {policy}",
    "tool.permission_denied": "└ Permission denied for {name}: {reason}",
    "tool.awaiting_approval": "├ Waiting for approval · {name}",
    "tool.approval_resolved": "├ Approval {outcome} · {name}",
    "tool.completed": "└ Completed {name} in {duration}",
    "tool.failed": "└ Failed {name} in {duration}: {message}",
    "tool.activity.inspecting": "Inspecting repository",
    "tool.activity.updating": "Updating workspace",
    "tool.activity.waiting": "Waiting for tasks",
    "tool.activity.working": "Agent activity",
    "tool.activity.read_files": "Read {count} files",
    "tool.activity.read_files.one": "Read 1 file",
    "tool.activity.searched": "Searched repository · {count}",
    "tool.activity.searched.one": "Searched repository once",
    "tool.activity.commands": "Ran {count} commands",
    "tool.activity.commands.one": "Ran 1 command",
    "tool.activity.edits": "Applied {count} workspace edits",
    "tool.activity.edits.one": "Applied 1 workspace edit",
    "tool.activity.actions": "Completed {count} actions",
    "tool.activity.actions.one": "Completed 1 action",
    "tool.peek.help": "↑↓ Select tool · Enter inspect · Esc summary",
    "tool.peek.tooltip.open": "Open a bounded tool preview",
    "tool.peek.tooltip.close": "Collapse the tool preview",
    "tool.peek.position": "{current}/{total}",
    "tool.peek.preview": "Preview",
    "tool.peek.output_empty": "No output",
    "tool.peek.lines_omitted": "… {count} more result lines",
    "tool.peek.result_truncated": "Result is truncated",
    "tool.peek.tree_summary": "{count} entries · depth {depth}",
    "tool.peek.grep_summary": "{count} matches · {files} files",
    "tool.peek.scanned_files": "Scanned {count} files",
    "tool.peek.file_summary": "{count} total lines",
    "tool.peek.requested_range": "Requested lines {start}–{end}",
    "tool.peek.exit_code": "Exit code {code}",
    "tool.peek.result_count": "{count} results",
    "tool.peek.permission_denied": "Permission denied · {reason}",
    "tool.peek.approval_required": "Waiting for approval",
    "tool.inspector.title": "Tool Inspector",
    "tool.inspector.tab.output": "Output [1]",
    "tool.inspector.tab.input": "Input [2]",
    "tool.inspector.tab.meta": "Meta [3]",
    "tool.inspector.help": "1/2/3 switches view · Ctrl+A selects all · Ctrl+C copies · Esc closes",
    "tool.inspector.copied": "Copied {characters} characters.",
    "tool.inspector.copy_unavailable": "Clipboard unavailable; sent a terminal copy request.",
    "tool.inspector.output_empty": "No output was returned.",
    "tool.inspector.workspace_changes": "Workspace changes",
    "tool.inspector.diff_truncated": "[Diff truncated by the bounded change report]",
    "tool.inspector.diff_unavailable": "[Diff unavailable: {reason}]",
    "tool.inspector.files_omitted": "[{count} files omitted by the bounded change report]",
    "tool.inspector.input_truncated": "[Input truncated at the Inspector display limit]",
    "tool.inspector.output_loading": "Loading the bounded, session-owned output artifact…",
    "tool.inspector.output_unavailable": "The output artifact is unavailable; showing the bounded tool result.",
    "tool.inspector.output_artifact_available": "A bounded output artifact is available and will be loaded in this Inspector.",
    "tool.inspector.output_read_truncated": "Output is truncated at the 256 KiB Inspector read limit.",
    "tool.inspector.output_stored_truncated": "The stored output artifact was truncated at its bounded storage limit.",
    "tool.inspector.output_preview_truncated": "Only the bounded tool result is available; additional output may exist.",
    "value.unknown": "unknown",
    "command_hint.tab": "Tab complete",
    "command.tasks_arguments": "/tasks does not accept arguments.",
    "command.arguments": "/{command} does not accept arguments.",
    "command.help": "Commands: /help, /status, /recover [inspect|abandon TURN_ID|retry TURN_ID], /compact (alias /context), /mode [MODE], /plan [DESCRIPTION], /view-plan (alias /show-plan), /execute-plan (alias /run-plan), /schedule-plan (alias /queue-plan), /run-task TASK_ID, /subagent PROMPT, /subagents [ACTION TASK_ID], /tasks, /auto-wake [on|off], /view-task TASK_ID, /settings (alias /setting), /provider [PROFILE] (alias /model), /effort [LEVEL] (alias /reasoning), /sessions [QUERY], /resume [SESSION_ID], /undo, /rename TITLE (alias /title), /cancel, /clear, /quit (alias /exit).",
    "workspace_undo.restored": "Workspace restored to the state before the latest turn.",
    "workspace_undo.live": "Workspace undo is unavailable while a live mutator is running.",
    "workspace_undo.none": "No workspace undo is available.",
    "workspace_undo.unavailable": "Workspace undo is unavailable: {reason}.",
    "context.compaction_result": "Context compaction: {status}.",
    "context.compaction_failed": "Context compaction failed: {error}",
    "context.preflight.compaction_required": "Context pressure detected; compacting before continuing.",
    "context.preflight.blocked": "The context request exceeds the available budget; the turn stopped safely.",
    "context.preflight.unknown": "Provider context capacity is unknown; continuing without a numeric safety check.",
    "subagents.actions_unavailable": "Subagent lifecycle controls are unavailable in this session.",
    "subagents.actions_usage": "Usage: /subagents ACTION TASK_ID (resume, fork, delete).",
    "subagents.actions.forked": "Forked child session {session_id}; it was not opened automatically.",
    "subagents.actions.deleted": "Deleted child session {session_id}.",
    "command.status": "Provider: {provider}/{model} · Context: {context} · Effort: {effort} · Mode: {mode} · Session: {session}{profile} · CWD: {cwd}",
    "command.not_created": "not created",
    "command.profile": " · Profile: {profile}",
    "command.unknown": "Unknown command: /{command}. Use /help.",
    "transcript.cleared": "Transcript cleared.",
    "provider.switch_unavailable": "Provider switching is unavailable.",
    "provider.switch_running": "Cannot switch provider while a turn is running.",
    "provider.default_save_failed": "The provider changed for this run, but the default could not be saved: {error}",
    "effort.unavailable": "Reasoning-effort control is unavailable.",
    "effort.switch_running": "Cannot change reasoning effort while a turn is running.",
    "effort.invalid": "Unknown effort {value!r}. Choose one of: {levels}.",
    "effort.already_selected": "Reasoning effort is already {glyph} {effort}.",
    "effort.changed": "Reasoning effort changed to {glyph} {effort}; it applies from the next model step.",
    "effort.already_selected_ultracode": "Reasoning effort is already {requested}.",
    "effort.changed_ultracode": "Reasoning effort changed to {requested}; it applies from the next model step.",
    "effort.save_failed": "The effort changed for this run, but the preference could not be saved: {error}",
    "mode.current": "Current mode: {mode}. Available modes: {modes}.",
    "mode.invalid": "Unknown mode {value!r}. Choose one of: {modes}.",
    "mode.unavailable": "Interaction-mode control is unavailable.",
    "mode.switch_running": "Cannot change mode while a turn is running.",
    "mode.already_selected": "Interaction mode is already {glyph} {mode}.",
    "mode.changed": "Interaction mode changed to {glyph} {mode}.",
    "mode.changed_auto_limited": "Auto mode selected in its safe preview: reads and edits are automatic, while commands and network effects still require approval. The safety classifier is not implemented yet.",
    "mode.save_failed": "The mode changed for this run, but the preference could not be saved: {error}",
    "mode.limited": "limited",
    "plan.none": "No structured plan has been saved for this session.",
    "plan.heading": "Updated plan:",
    "plan.purpose": "Purpose: {explanation}",
    "plan.step": "{index}. [{status}] {step}",
    "plan.comment": "   ↳ Comment: {content}",
    "plan.comment_unavailable": "Plan comments are unavailable for this interface.",
    "plan.comment_usage": "Usage: /comment-plan STEP COMMENT",
    "plan.comment_step_invalid": "Plan step {index} does not exist.",
    "plan.comment_added": "Saved comment for plan step {index}.",
    "plan.status.pending": "pending",
    "plan.status.in_progress": "in progress",
    "plan.status.completed": "completed",
    "plan.execution_unavailable": "Plan execution is unavailable for this interface.",
    "plan.execution_user": "Execute the current structured plan.",
    "plan.execution_requested": "Execution started from the current structured plan in accept-edits mode.",
    "plan.scheduled": "Queued plan task {task_id}. Run /run-task {task_id} when ready.",
    "plan.task_execution_user": "Run queued plan task {task_id}.",
    "provider.already_selected": "Provider profile {profile} is already selected.",
    "provider.switched": "Provider profile switched to {profile} ({provider}/{model}).{stopped}",
    "provider.switched_saved": "Provider profile switched to {profile} ({provider}/{model}). The previous session {session_id} remains saved; the next prompt starts a new conversation.{stopped}",
    "tasks.stopped_one": " Stopped 1 background task from the previous session.",
    "tasks.stopped_many": " Stopped {count} background tasks from the previous session.",
    "session.resume_unavailable": "Interactive session resume is unavailable.",
    "session.resume_running": "Cannot resume a session while a turn is running.",
    "session.none": "No sessions found for this workspace.",
    "session.none_matching": "No sessions found for this workspace matching {query!r}.",
    "session.rename_unavailable": "Interactive session rename is unavailable.",
    "session.rename_running": "Cannot rename a session while a turn is running.",
    "session.renamed": "Session {session_id} renamed to {title!r}.",
    "session.already_open": "Session {session_id} is already open.",
    "session.profile": "profile {profile}",
    "session.profile_unavailable": "profile {profile}; source profile {source} is not ready locally",
    "session.previous_saved": " Previous session {session_id} remains saved.",
    "session.resumed": "Resumed session {session_id} with {profile_note} ({provider}/{model}).{previous}{stopped}",
    "tasks.unavailable": "Task visibility is unavailable.",
    "tasks.none": "No tasks for the current session.",
    "tasks.heading": "Tasks:\n{lines}",
    "tasks.omitted": "... {count} older task(s) omitted",
    "tasks.summary": "{task_id} · {status}{exit_note} · {bytes} output bytes{truncated} · started {started}",
    "tasks.exit": " · exit {code}",
    "tasks.truncated": " (preview truncated)",
    "tasks.status.running": "running",
    "tasks.status.queued": "queued",
    "tasks.status.completed": "completed",
    "tasks.status.failed": "failed",
    "tasks.status.timed_out": "timed out",
    "tasks.status.cancelled": "cancelled",
    "tasks.kind.plan_execution": "plan execution",
    "tasks.kind.subagent": "subagent",
    "tasks.session.summary": "{task_id} · {kind} · {status} · started {started}{finished}{plan}",
    "tasks.session.finished": " · finished {finished}",
    "tasks.session.plan_revision": " · plan revision {fingerprint} · {completed}/{total} completed",
    "tasks.view.usage": "Usage: /view-task TASK_ID",
    "tasks.view.not_found": "No durable task {task_id!r} exists in the current session.",
    "tasks.view.no_plan": "Task {task_id!r} has no saved plan snapshot.",
    "tasks.view.heading": "Plan execution task {task_id}",
    "tasks.view.lifecycle": "{kind} · {status} · started {started}{finished}",
    "tasks.view.revision": "Plan revision {fingerprint}",
    "tasks.view.snapshot": "Saved plan snapshot (reference only):",
    "tasks.view.purpose": "Purpose: {explanation}",
    "tasks.view.step": "{index}. [{status}] {step}",
    "tasks.view.reference": "This historical plan is read-only; it does not change the current plan or execute work.",
    "tasks.run.usage": "Usage: /run-task TASK_ID",
    "tasks.run.not_found": "No durable task {task_id!r} exists in the current session.",
    "tasks.run.not_plan": "Task {task_id!r} is not a plan execution task.",
    "tasks.run.not_queued": "Task {task_id!r} is not queued; only queued tasks can be started.",
    "tasks.completion.completed": "Background task {task_id} completed{exit_note}.",
    "tasks.completion.failed": "Background task {task_id} failed{exit_note}.",
    "tasks.completion.timed_out": "Background task {task_id} timed out{exit_note}.",
    "tasks.completion.cancelled": "Background task {task_id} was cancelled{exit_note}.",
    "tasks.completion.exit": " (exit {code})",
    "background_wake.current": "Background-task auto-wake is {policy} for this TUI session.",
    "background_wake.invalid": "Unknown auto-wake policy {value!r}; use on or off.",
    "background_wake.already_selected": "Background-task auto-wake is already {policy}.",
    "background_wake.changed": "Background-task auto-wake is now {policy} for this TUI session.",
    "background_wake.policy.enabled": "enabled",
    "background_wake.policy.disabled": "disabled",
    "background_wake.started": "Background task completed; waking the model once.",
    "restore.result": "Restored result for {name}.",
    "restore.request": "Restored tool request: {names}.",
    "restore.truncated": "... [restored message truncated]",
    "settings.changed": "Interface language changed to {language}.",
    "settings.save_failed": "The language changed for this session, but the preference could not be saved: {error}",
}

_CHINESE: Final[dict[str, str]] = {
    "subtitle": "终端编程智能体",
    "prompt.placeholder": "询问 Neuro Code……（输入 /help 查看命令）",
    "shortcuts": "^C 取消  ^Q 退出  F8 复制  Shift+Tab 模式  ^P 模型  ^E 强度  ^R 会话  ^, 设置  ^L 清屏",
    "runtime.help": "F1 帮助",
    "transcript_copy.title": "复制会话记录",
    "transcript_copy.help": "拖动鼠标或使用 Shift+方向键选择；Ctrl+A 全选；Ctrl+C 复制；Esc 关闭。",
    "transcript_copy.select_first": "请先选择要复制的会话文本。",
    "transcript_copy.copied": "已复制 {characters} 个字符。",
    "transcript_copy.clipboard_unavailable": "当前没有可用的系统剪贴板支持，已向终端发送复制请求；该终端可能不支持复制。",
    "transcript_copy.empty": "当前会话记录为空。",
    "assistant.copy_hint": "双击回复即可选择并复制。",
    "label.error": "错误",
    "label.status": "状态",
    "label.tool": "工具",
    "approval.title": "需要工具授权",
    "approval.tool": "工具：{tool}",
    "approval.policy": "策略：{policy}",
    "approval.allow_once": "仅允许本次 [A]",
    "approval.allow_session": "本会话允许相同操作 [S]",
    "approval.scope.heading": "其他范围授权（仅显示安全候选）：",
    "approval.scope.workspace_edits": "允许在 {root} 中进行工作区编辑",
    "approval.scope.command_family": "允许在 {root} 中运行 {family} 命令",
    "approval.unscoped": "该操作无法安全限定范围，因此不能授予会话级权限。",
    "approval.deny": "拒绝 [D/Esc/Ctrl+C]",
    "provider.title": "选择供应商配置",
    "provider.help": "切换配置会开始新对话。按 Esc/Ctrl+C 关闭选择器。",
    "marker.current": "当前",
    "marker.default": "默认",
    "marker.unavailable": "不可用",
    "marker.credential_missing": "缺少凭据",
    "session.search": "会话搜索：{query}",
    "session.title": "当前工作区会话",
    "session.search_placeholder": "输入文字筛选会话……",
    "session.help": "仅列出当前工作区的会话。使用 /sessions 查询词筛选；按 Esc/Ctrl+C 关闭。",
    "session.resume_via": "通过 {profile} 恢复",
    "session.legacy_sandbox": "旧版沙箱",
    "session.sandbox": "沙箱 {profile}",
    "session.sandbox_off": "沙箱关闭 · 无操作系统隔离",
    "session.restart_required": "需要重启",
    "terminal.title": "附加终端",
    "terminal.none": "没有附加终端。",
    "terminal.session": "{marker}{terminal_id} · 进程 {pid} · {status}",
    "terminal.running": "运行中",
    "terminal.exited": "已退出（{code}）",
    "terminal.status_unknown": "状态不可用",
    "terminal.output_empty": "暂无输出。",
    "terminal.output_dropped": "已丢弃 {bytes} 字节终端输出。",
    "terminal.help": "Ctrl+Shift+T 聚焦 · Ctrl+] / Ctrl+[ 选择 · Ctrl+Shift+R 调整大小 · Ctrl+Shift+X 停止 · Esc 返回聊天",
    "terminal.input_placeholder": "向当前选中的终端输入内容…",
    "terminal.unavailable": "当前绑定不支持附加终端。",
    "terminal.input_too_large": "终端输入过大。",
    "terminal.input_failed": "终端输入失败：{error}",
    "terminal.stop_failed": "终端停止失败：{error}",
    "terminal.stopped": "已停止附加终端 {terminal_id}。",
    "terminal.resize_failed": "终端调整大小失败：{error}",
    "terminal.resized": "附加终端已调整为 {columns}×{rows}。",
    "settings.title": "设置",
    "settings.description": "选择一级设置分类，进入后再修改具体选项。",
    "settings.category.language": "界面语言  ·  {current}",
    "settings.category.providers": "模型供应商  ·  配置、协议、接口地址与 API 密钥",
    "settings.category.network": "网络与代理  ·  默认连接策略",
    "settings.category.background_wake": "后台任务唤醒  ·  全局默认和供应商覆盖",
    "settings.category.language.label": "界面语言",
    "settings.category.agent_reasoning.label": "Agent / 推理强度",
    "settings.category.agent_reasoning.value": "{effort}",
    "settings.category.agent_interaction_mode.label": "Agent / 交互模式",
    "settings.category.agent_interaction_mode.value": "{mode}",
    "settings.category.providers.label": "模型供应商",
    "settings.category.network.label": "网络与代理",
    "settings.category.background_wake.label": "后台任务唤醒",
    "settings.category.providers.value": "管理",
    "settings.category.network.value": "配置",
    "settings.category.background_wake.value": "配置",
    "settings.current": "当前",
    "settings.help": "按 Esc/Ctrl+C 关闭设置。",
    "settings.language.title": "界面语言",
    "settings.language.description": "选择整个 TUI 使用的界面语言。",
    "settings.language.help": "选择会立即生效，并用于以后启动的 TUI。",
    "settings.back": "返回",
    "provider_settings.first_run_title": "设置 Neuro Code",
    "provider_settings.title": "模型供应商",
    "provider_settings.description": "选择已保存的配置进行编辑，或创建新配置。API 密钥与普通配置分开保存，且不会在这里回显。",
    "provider_settings.empty": "尚未保存受管供应商配置。",
    "provider_settings.preset.openai": "OpenAI Responses",
    "provider_settings.preset.compatible": "兼容 Chat",
    "provider_settings.preset.deepseek": "DeepSeek",
    "provider_settings.preset.anthropic": "Anthropic",
    "provider_settings.preset.gemini": "Gemini",
    "provider_settings.preset.xai": "xAI",
    "provider_settings.preset.kimi": "Kimi",
    "provider_settings.preset.glm": "GLM",
    "provider_settings.preset.minimax": "MiniMax",
    "provider_settings.preset.ark": "火山方舟",
    "provider_settings.preset.qianfan": "百度千帆",
    "provider_settings.preset.bailian": "阿里云 Model Studio",
    "provider_settings.preset.tokenhub": "腾讯 TokenHub",
    "provider_settings.name": "配置名称（字母、数字、点、下划线或连字符）",
    "provider_settings.field.name": "供应商配置",
    "provider_settings.field.model": "模型",
    "provider_settings.field.base_url": "API 地址",
    "provider_settings.field.api_key": "认证",
    "provider_settings.field.context_window": "上下文窗口",
    "provider_settings.endpoint.title": "接口 / 地域变体",
    "provider_settings.protocol.title": "此模型使用的协议",
    "provider_settings.protocol.option.recommended": "自动 / 推荐",
    "provider_settings.protocol.option.chat": "OpenAI Chat",
    "provider_settings.protocol.option.responses": "OpenAI Responses",
    "provider_settings.protocol.option.anthropic": "Anthropic Messages",
    "provider_settings.protocol.option.gemini": "Gemini generateContent",
    "provider_settings.protocol.option.gemini_interactions": "Gemini Interactions",
    "provider_settings.protocol.unknown": "尚未确认该模型的协议支持；仅应在有文档或手工证据时继续。",
    "provider_settings.model": "模型标识",
    "provider_settings.model.openai": "模型标识（例如 gpt-5.4）",
    "provider_settings.model.compatible": "Chat Completions 模型标识",
    "provider_settings.model.deepseek": "deepseek-v4-pro 或 deepseek-v4-flash",
    "provider_settings.model.anthropic": "Anthropic 模型标识",
    "provider_settings.model.gemini": "Gemini 模型标识",
    "provider_settings.model.xai": "xAI 模型标识",
    "provider_settings.model.kimi": "Kimi 模型标识（例如 kimi-k3 或 kimi-k2.6）",
    "provider_settings.model.glm": "GLM 模型标识（例如 glm-5.3）",
    "provider_settings.model.minimax": "MiniMax 模型标识（例如 MiniMax-M3）",
    "provider_settings.model.ark": "方舟模型或模型接入标识",
    "provider_settings.model.qianfan": "千帆模型标识",
    "provider_settings.model.bailian": "Model Studio 模型标识",
    "provider_settings.model.tokenhub": "TokenHub 模型或服务标识",
    "provider_settings.protocol.openai": "OpenAI Responses API · 请求会发送到 /responses。",
    "provider_settings.protocol.compatible": "OpenAI 兼容 Chat Completions · 请求会发送到 /chat/completions。",
    "provider_settings.protocol.deepseek": "DeepSeek 的 OpenAI 兼容 Chat Completions · 请求会发送到 /chat/completions；使用 https://api.deepseek.com 与当前 DeepSeek 模型标识。",
    "provider_settings.protocol.anthropic": "Anthropic Messages API · 请求会发送到 /v1/messages。",
    "provider_settings.protocol.gemini": "Gemini generateContent API。",
    "provider_settings.protocol.xai": "使用 xAI 方言的 xAI Responses API。",
    "provider_settings.protocol.kimi": "Kimi 的 OpenAI 兼容 Chat Completions · 当前模型从 /v1/models 发现。",
    "provider_settings.protocol.glm": "GLM 的 OpenAI 兼容 Chat Completions · 因没有假定稳定的模型目录接口，使用官方静态模型列表。",
    "provider_settings.protocol.minimax": "MiniMax 的 OpenAI 兼容 Chat Completions · 当前模型从 /v1/models 发现。",
    "provider_settings.protocol.ark": "方舟推理服务 · 请按所选模型证据选择 Chat 或 Responses；本轮不会启用平台内置联网工具。",
    "provider_settings.protocol.ark.chat": "方舟 OpenAI 兼容 Chat Completions · 请求使用所选方舟接口。",
    "provider_settings.protocol.ark.responses": "方舟 Responses API · 通过共享 Responses 适配器支持便携式函数调用；平台内置工具保持关闭。",
    "provider_settings.protocol.qianfan": "千帆推理服务 · 会按所选模型的证据校验协议支持度。",
    "provider_settings.protocol.qianfan.chat": "千帆 OpenAI 兼容 Chat Completions。",
    "provider_settings.protocol.qianfan.responses": "千帆 OpenAI 兼容 Responses · 只有官方明确列出的模型才标记为支持。",
    "provider_settings.protocol.qianfan.anthropic": "千帆 Anthropic 兼容 Messages · 只表示线协议兼容，不继承 Anthropic 服务端工具。",
    "provider_settings.protocol.bailian": "阿里云 Model Studio · 接口和计费计划范围属于配置档案身份。",
    "provider_settings.protocol.bailian.chat": "Model Studio OpenAI 兼容 Chat Completions。",
    "provider_settings.protocol.bailian.responses": "Model Studio OpenAI 兼容 Responses · 只支持便携式 Responses，平台托管工具保持关闭。",
    "provider_settings.protocol.bailian.anthropic": "Model Studio Anthropic 兼容 Messages · 此接口不提供 /v1/models 发现。",
    "provider_settings.protocol.tokenhub": "TokenHub · Responses 是原生、兼容转换还是不支持，由所选模型证据决定。",
    "provider_settings.protocol.tokenhub.chat": "TokenHub OpenAI 兼容 Chat Completions。",
    "provider_settings.protocol.tokenhub.responses": "TokenHub OpenAI Responses · 模型证据区分原生支持与兼容转换支持。",
    "provider_settings.protocol.tokenhub.anthropic": "TokenHub Anthropic 兼容 Messages · 认证交给共享 Anthropic 适配器。",
    "provider_settings.base_url": "API 基础地址",
    "provider_settings.api_key": "API 密钥（留空则保留已保存的密钥）",
    "provider_settings.api_key_required": "新配置必须填写 API 密钥。",
    "provider_settings.context_window": "上下文容量（token，例如 128000）",
    "provider_settings.context_window_hint": "可选；填写后状态栏才能显示准确上下文百分比。此能力数据只在本地使用，绝不会发送给供应商。",
    "provider_settings.context_window_invalid": "上下文容量必须是正整数。",
    "provider_settings.connection.test": "测试连接并加载模型",
    "provider_settings.connection.testing": "正在测试连接……",
    "provider_settings.connection.success": "连接成功，已加载 {count} 个模型。可在下方选择，也可手动输入标识。",
    "provider_settings.connection.success_empty": "连接成功，但供应商没有返回可选模型；请手动输入模型标识。",
    "provider_settings.connection.success_selected": "连接成功，已加载 {count} 个模型，并确认 {model!r} 可用。",
    "provider_settings.connection.success_missing": "连接成功并加载了 {count} 个模型，但列表中没有 {model!r}。可以选择下方模型；若供应商支持未公开模型，也可保留手动标识。",
    "provider_settings.connection.selected": "已选择模型 {model!r}，保存配置后即可使用。",
    "provider_settings.connection.stale": "连接测试期间草稿已改变，旧结果已丢弃；准备好后请重新测试。",
    "provider_settings.connection.static": "正在显示有界的官方模型列表。未测试凭据；仍可手动输入模型标识。",
    "provider_settings.connection.manual_only": "此协议没有安全的推理模型目录接口。请手动填写已有证据的模型标识；本次未发起凭据请求。",
    "provider_settings.connection.fallback": "模型发现不可用，正在显示有界的官方回退列表；凭据未验证，仍可手动输入模型标识。",
    "provider_settings.connection.truncated": " 有界列表只显示前 200 个标识。",
    "provider_settings.connection.error.authentication": "认证失败（HTTP {status}）。请检查 API 密钥和账户权限。",
    "provider_settings.connection.error.endpoint": "未找到模型目录接口（HTTP {status}）。请检查基础地址和所选 API 协议；对于没有目录接口的兼容服务器，仍可手动输入模型。",
    "provider_settings.connection.error.timeout": "连接供应商超时。请检查网络、代理和接口地址。",
    "provider_settings.connection.error.rate_limit": "供应商限制了本次连接测试（HTTP {status}），请稍后重试。",
    "provider_settings.connection.error.server": "供应商返回服务端错误（HTTP {status}），请稍后重试。",
    "provider_settings.connection.error.http": "供应商拒绝了模型目录请求（HTTP {status}）。请检查接口地址和账户权限。",
    "provider_settings.connection.error.proxy": "代理连接失败：{detail}",
    "provider_settings.connection.error.network": "无法连接供应商：{detail}",
    "provider_settings.connection.error.response_too_large": "供应商模型目录超过了安全的一兆字节响应上限。",
    "provider_settings.connection.error.invalid_response": "供应商返回了无效的模型目录。请确认基础地址与所选协议匹配。",
    "provider_settings.connection.error.unknown": "供应商连接测试失败：{detail}",
    "provider_settings.proxy.title": "供应商代理覆盖",
    "provider_settings.proxy.inherit": "使用全局默认",
    "provider_settings.proxy.environment": "使用环境变量",
    "provider_settings.proxy.direct": "直接连接",
    "provider_settings.proxy.explicit": "指定变量",
    "provider_settings.proxy.environment_variable": "代理 URL 环境变量（例如 NEURO_DEEPSEEK_PROXY_URL）",
    "provider_settings.proxy.hint.environment": "保存前使用并校验 HTTP_PROXY、HTTPS_PROXY、ALL_PROXY、NO_PROXY 及证书环境设置。",
    "provider_settings.proxy.hint.direct": "这个供应商忽略代理和证书环境设置，直接连接。",
    "provider_settings.proxy.hint.explicit": "从指定环境变量读取一个代理 URL；URL 与其中的凭据不会保存或显示。",
    "provider_settings.proxy.hint.inherit": "使用全局默认策略：{policy}。只有这个供应商需要不同网络路径时，才设置覆盖。",
    "provider_settings.background_wake.title": "后台任务唤醒覆盖",
    "provider_settings.background_wake.inherit": "使用全局默认",
    "provider_settings.background_wake.disabled": "禁用",
    "provider_settings.background_wake.enabled": "启用",
    "provider_settings.background_wake.hint": "选中这个供应商时使用此覆盖；否则使用全局默认策略。",
    "network_settings.title": "网络与代理",
    "network_settings.description": "设置受管供应商的默认网络路径。单个供应商可以显式覆盖，但不会保存代理 URL。",
    "network_settings.default_policy": "全局默认策略",
    "network_settings.environment": "使用环境变量",
    "network_settings.direct": "直接连接",
    "network_settings.explicit": "指定变量",
    "network_settings.environment_variable": "代理 URL 环境变量（例如 NEURO_CODE_PROXY_URL）",
    "network_settings.hint.environment": "保存前使用并校验 HTTP_PROXY、HTTPS_PROXY、ALL_PROXY、NO_PROXY 及证书环境设置。",
    "network_settings.hint.direct": "默认忽略代理和证书环境设置；单个供应商仍可选择其他路径。",
    "network_settings.hint.explicit": "从指定环境变量读取一个代理 URL；URL 与其中的凭据不会保存或显示。",
    "network_settings.policy.environment": "环境变量设置",
    "network_settings.policy.direct": "直接连接",
    "network_settings.policy.explicit": "指定的代理变量",
    "network_settings.save": "保存网络默认策略",
    "background_wake_settings.title": "后台任务唤醒",
    "background_wake_settings.description": "选择空闲会话的全局默认策略；单个供应商配置可以覆盖它。",
    "background_wake_settings.default_policy": "全局默认策略",
    "background_wake_settings.disabled": "禁用",
    "background_wake_settings.enabled": "启用",
    "background_wake_settings.hint.disabled": "后台任务完成仍会提示，但默认不会自主启动模型轮次。",
    "background_wake_settings.hint.enabled": "空闲 TUI 对每批待处理完成项最多启动一次有界的仅模型唤醒。",
    "background_wake_settings.save": "保存唤醒默认策略",
    "provider_settings.new": "新建配置",
    "provider_settings.delete": "删除配置",
    "provider_settings.delete_confirm": "确认删除",
    "provider_settings.delete_warning": "是否删除配置 {profile!r} 及其已保存 API 密钥？再次点击“确认删除”继续。",
    "provider_settings.save_use": "保存并使用",
    "effort.title": "思考强度",
    "effort.description.low": "快速",
    "effort.description.medium": "均衡",
    "effort.description.high": "深入",
    "effort.description.xhigh": "复杂任务",
    "effort.description.max": "单智能体最大深度",
    "effort.description.ultracode": "自动有界委派",
    "effort.workflow_delegation": "有界路径",
    "effort.help": "从下一次模型步骤生效。Ultracode 会选择 MAIN_MAX 或现有的有界 Agent Swarm。",
    "interaction_mode.title": "交互模式",
    "interaction_mode.description.normal": "只读探索自动运行；副作用仍需授权。",
    "interaction_mode.description.accept-edits": "工作区编辑可以继续；其他副作用仍需授权。",
    "interaction_mode.description.plan": "只进行探索并准备计划，不产生副作用。",
    "interaction_mode.description.auto": "在所有显式边界内继续执行安全工作。",
    "interaction_mode.help": "从下一次模型步骤生效。Shift+Tab 与 /mode 使用同一项偏好。",
    "runtime.model": "模型",
    "runtime.context": "上下文",
    "runtime.context_unknown": "未知",
    "runtime.context_help_unknown": "当前供应商没有配置上下文窗口，因此无法计算占用百分比。",
    "runtime.context_help_estimated": "当前对话上下文估算约为 {used} / {window} token；模型步骤返回用量后会改用供应商数据。",
    "runtime.context_help_preflight": "当前请求压力估算约为 {used} / {window} token，包含输出保留值和安全余量。",
    "runtime.context_help_reported": "最近模型步骤后的对话上下文为 {used} / {window} 个供应商报告的 token。",
    "runtime.effort": "强度",
    "runtime.effort_help": "这是应用层审查策略。Ultracode 会持久化选择一条 MAIN_MAX 或有界 Agent Swarm 路径；MAX 仍是普通单智能体的最大深度。",
    "runtime.ultracode": "UltraCode",
    "runtime.ultracode.auto_routing": "自动",
    "runtime.ultracode.auto_routing_detail": "自动路由",
    "runtime.ultracode.main_max": "MAIN_MAX",
    "runtime.ultracode.swarm": "Swarm",
    "runtime.ultracode.provider_effort": "供应商 {effort}",
    "runtime.workspace": "工作区",
    "runtime.mode": "模式",
    "runtime.mode_help.normal": "Normal：只读工具自动运行；编辑和命令需要授权。",
    "runtime.mode_help.accept-edits": "Accept Edits：读取和工作区编辑自动运行；命令及其他副作用仍需授权。",
    "runtime.mode_help.plan": "Plan：只允许只读探索；所有带副作用的请求都会被拒绝。",
    "runtime.mode_help.auto": "Auto（受限预览）：读取和编辑自动运行；安全分类器实现前，命令和网络操作仍需授权。",
    "runtime.mode_help_auto_unrestricted": "本次 Auto 由 --always-approve 显式授权。显式 deny 规则和进程沙箱仍然有效；安全分类器尚未实现。",
    "startup.resumed": "已恢复会话 {session_id} · {provider}/{model} · {cwd}",
    "startup.ready": "已就绪 · {provider}/{model} · {cwd}",
    "session.stuck_recoverable": "上一次任务陷入重复循环，已安全暂停。你可以继续输入新的指令。",
    "session.budget_limited_recoverable": "上一次任务达到执行预算，已安全暂停。你可以继续输入新的指令。",
    "session.recovery.safe": "中断回合 {turn_id} 在模型输出前停止，可以安全重试。请使用 /recover retry {turn_id} 或 /recover abandon {turn_id}。",
    "session.recovery.retry_unavailable": "中断计划回合 {turn_id} 已安全保留，但计划回合暂不支持重试。请使用 /recover abandon {turn_id}。",
    "session.recovery.indeterminate": "中断回合 {turn_id} 在 {stage} 后状态不确定。不要重放；请先使用 /recover abandon {turn_id} 再继续。",
    "session.recovery.abandoned": "中断回合 {turn_id} 已被明确放弃。",
    "recovery.unavailable": "本次会话无法使用崩溃恢复控制。",
    "recovery.usage": "用法：/recover [inspect|abandon TURN_ID|retry TURN_ID]。",
    "recovery.none": "没有发现中断回合。",
    "recovery.item": "{turn_id} · {status} · 阶段={stage} · 输入={input_state} · retry={retry_available} · abandon={abandon_available} · {reason}",
    "turn.running": "已有一轮任务正在运行。",
    "turn.interjection_queued": "已排队，当前回答完成后执行。",
    "turn.interjection_restored": "已将排队提示恢复到输入框。",
    "turn.interjections_restored": "{count} 条排队提示已恢复到草稿，不会自动发送。",
    "turn.interjection_limit": "排队提示已达上限，请等待当前轮次完成。",
    "turn.waiting": "思考中……",
    "turn.finalizing": "正在安全收尾……",
    "turn.activity.thinking": "正在处理",
    "turn.activity.model": "正在等待模型",
    "turn.activity.reasoning": "正在推理",
    "turn.activity.responding": "正在生成回答",
    "turn.activity.continuing": "正在继续任务",
    "turn.activity.waiting_input": "等待你的输入",
    "turn.activity.finalizing": "正在安全收尾",
    "turn.activity.orchestrating": "正在进行任务编排",
    "turn.activity.completed": "正在完成本轮",
    "turn.activity.failed": "正在停止本轮",
    "turn.activity.running_tool": "正在运行 {tool}",
    "turn.activity.waiting_tool": "正在通过 {tool} 等待",
    "turn.provider_balance_recoverable": "模型服务商因账户余额不足拒绝了本次请求。当前会话仍可继续；请充值或切换服务商后再发送新的指令。",
    "turn.provider_failure_recoverable": "模型服务商请求失败。当前会话仍可继续；请检查服务商设置或切换服务商后重试。",
    "turn.stuck_recoverable": "任务陷入重复循环，已安全停止。你可以继续输入新的指令。",
    "turn.budget_limited_recoverable": "已达到本轮执行预算，已安全停止。你可以继续输入新的指令。",
    "turn.no_response": "（没有文本回答）",
    "turn.cancelled": "本轮已取消。",
    "turn.reasoning": "正在推理……",
    "turn.thinking_completed": "推理结束 · {duration} · 第 {step} 个模型步骤",
    "turn.completed": "本轮完成 · 用时 {duration} · {steps} 个模型步骤",
    "turn.cancel_requested": "已请求取消。",
    "interaction.submitted": "回答已提交，继续处理任务。",
    "turn.draft_cleared": "草稿已清除。",
    "turn.draft_restored": "已将取消前的提示恢复到草稿。",
    "turn.draft_preserved": "输入框已有更新草稿；已取消的提示仍保留在上方记录中。",
    "turn.none_running": "当前没有运行中的任务。",
    "subagent.usage": "/subagent 需要提示词。",
    "subagent.unavailable": "本次会话无法使用只读子代理。",
    "subagent.session_required": "请先创建或恢复会话,再运行子代理。",
    "subagent.started": "只读子代理已启动。",
    "subagent.completed": "只读子代理已完成 · {steps} 个步骤。",
    "subagent.finished": "只读子代理以{status}结束 · {steps} 个步骤。",
    "subagent.truncated": "只读子代理响应已限制在安全显示范围内。",
    "subagent.cancelled": "只读子代理已取消。",
    "subagent.failed": "只读子代理失败：{error}",
    "subagents.unavailable": "本次会话无法查看子代理关系。",
    "subagents.session_required": "请先创建或恢复会话,再查看子代理。",
    "subagents.none": "当前会话没有子代理关系。",
    "subagents.heading": "子代理关系（只读）：\n{lines}",
    "subagents.summary": "{task_id} → {child_session_id} · {provider}/{model} · {status} · 创建 {created} · 更新 {updated} · 可用动作：{actions}",
    "subagents.actions.none": "无",
    "provider.failed": "供应商 {provider} 在输出前失败：{message}",
    "provider.selected": "已选择供应商 {provider}/{model}。",
    "provider.fallback_selected": "已选择备用供应商 {provider}/{model}。",
    "tool.hosted_started": "● 托管工具 {name}",
    "tool.hosted_completed": "└ {name} 完成 · {duration}",
    "tool.requested": "● {invocation}",
    "tool.permission_allowed": "├ 已允许 · {policy}",
    "tool.permission_denied": "└ {name} 权限被拒绝：{reason}",
    "tool.awaiting_approval": "├ 等待授权 · {name}",
    "tool.approval_resolved": "├ 授权结果 {outcome} · {name}",
    "tool.completed": "└ {name} 完成 · {duration}",
    "tool.failed": "└ {name} 失败 · {duration}：{message}",
    "tool.activity.inspecting": "正在检查仓库",
    "tool.activity.updating": "正在更新工作区",
    "tool.activity.waiting": "正在等待任务",
    "tool.activity.working": "Agent 活动",
    "tool.activity.read_files": "已查看 {count} 个文件",
    "tool.activity.read_files.one": "已查看 1 个文件",
    "tool.activity.searched": "已搜索仓库 {count} 次",
    "tool.activity.searched.one": "已搜索仓库 1 次",
    "tool.activity.commands": "已运行 {count} 条命令",
    "tool.activity.commands.one": "已运行 1 条命令",
    "tool.activity.edits": "已执行 {count} 次工作区编辑",
    "tool.activity.edits.one": "已执行 1 次工作区编辑",
    "tool.activity.actions": "已完成 {count} 项操作",
    "tool.activity.actions.one": "已完成 1 项操作",
    "tool.peek.help": "↑↓ 选择工具 · Enter 查看详情 · Esc 返回摘要",
    "tool.peek.tooltip.open": "打开有界工具预览",
    "tool.peek.tooltip.close": "收起工具预览",
    "tool.peek.position": "{current}/{total}",
    "tool.peek.preview": "预览",
    "tool.peek.output_empty": "没有输出",
    "tool.peek.lines_omitted": "……其余 {count} 行结果",
    "tool.peek.result_truncated": "结果已截断",
    "tool.peek.tree_summary": "{count} 个条目 · 深度 {depth}",
    "tool.peek.grep_summary": "{count} 个匹配 · {files} 个文件",
    "tool.peek.scanned_files": "已扫描 {count} 个文件",
    "tool.peek.file_summary": "共 {count} 行",
    "tool.peek.requested_range": "请求范围：第 {start}–{end} 行",
    "tool.peek.exit_code": "退出码 {code}",
    "tool.peek.result_count": "{count} 项结果",
    "tool.peek.permission_denied": "权限已拒绝 · {reason}",
    "tool.peek.approval_required": "正在等待授权",
    "tool.inspector.title": "工具检查器",
    "tool.inspector.tab.output": "输出 [1]",
    "tool.inspector.tab.input": "输入 [2]",
    "tool.inspector.tab.meta": "元数据 [3]",
    "tool.inspector.help": "1/2/3 切换视图 · Ctrl+A 全选 · Ctrl+C 复制 · Esc 关闭",
    "tool.inspector.copied": "已复制 {characters} 个字符。",
    "tool.inspector.copy_unavailable": "剪贴板不可用；已向终端发送复制请求。",
    "tool.inspector.output_empty": "工具没有返回输出。",
    "tool.inspector.workspace_changes": "工作区变更",
    "tool.inspector.diff_truncated": "[diff 已被有界变更报告截断]",
    "tool.inspector.diff_unavailable": "[diff 不可用：{reason}]",
    "tool.inspector.files_omitted": "[有界变更报告省略了 {count} 个文件]",
    "tool.inspector.input_truncated": "[输入已在 Inspector 显示上限处截断]",
    "tool.inspector.output_loading": "正在读取受限且属于当前会话的输出 artifact……",
    "tool.inspector.output_unavailable": "输出 artifact 不可用；当前显示受限的工具结果。",
    "tool.inspector.output_artifact_available": "存在受限的输出 artifact，将仅在本 Inspector 中读取。",
    "tool.inspector.output_read_truncated": "输出已在 Inspector 的 256 KiB 读取上限处截断。",
    "tool.inspector.output_stored_truncated": "保存的输出 artifact 已在受限存储上限处截断。",
    "tool.inspector.output_preview_truncated": "当前只有受限的工具结果，可能仍有其他输出。",
    "value.unknown": "未知",
    "command_hint.tab": "Tab 补全",
    "command.tasks_arguments": "/tasks 不接受参数。",
    "command.arguments": "/{command} 不接受参数。",
    "command.help": "命令：/help、/status、/recover [inspect|abandon TURN_ID|retry TURN_ID]、/compact（别名 /context）、/mode [模式]、/plan [说明]、/view-plan（别名 /show-plan）、/execute-plan（别名 /run-plan）、/schedule-plan（别名 /queue-plan）、/run-task TASK_ID、/subagent PROMPT、/subagents [ACTION TASK_ID]、/tasks、/auto-wake [on|off]、/view-task TASK_ID、/settings（别名 /setting）、/provider [配置]（别名 /model）、/effort [等级]（别名 /reasoning）、/sessions [查询词]、/resume [会话 ID]、/undo、/rename 标题（别名 /title）、/cancel、/clear、/quit（别名 /exit）。",
    "workspace_undo.restored": "工作区已恢复到最近一次回合之前的状态。",
    "workspace_undo.live": "存在仍在运行的变更进程，当前无法撤销工作区。",
    "workspace_undo.none": "没有可用的工作区撤销。",
    "workspace_undo.unavailable": "工作区撤销不可用：{reason}。",
    "context.compaction_result": "上下文压缩：{status}。",
    "context.compaction_failed": "上下文压缩失败：{error}",
    "context.preflight.compaction_required": "检测到上下文压力；正在压缩后继续。",
    "context.preflight.blocked": "上下文请求超出可用预算；已安全停止本轮。",
    "context.preflight.unknown": "供应商上下文容量未知；继续执行，但不显示数值安全判断。",
    "subagents.actions_unavailable": "本次会话无法执行子代理生命周期操作。",
    "subagents.actions_usage": "用法：/subagents ACTION TASK_ID（resume、fork、delete）。",
    "subagents.actions.forked": "已分叉子会话 {session_id}，不会自动打开。",
    "subagents.actions.deleted": "已删除子会话 {session_id}。",
    "command.status": "供应商：{provider}/{model} · 上下文：{context} · 强度：{effort} · 模式：{mode} · 会话：{session}{profile} · 工作目录：{cwd}",
    "command.not_created": "尚未创建",
    "command.profile": " · 配置：{profile}",
    "command.unknown": "未知命令：/{command}。请使用 /help。",
    "transcript.cleared": "对话记录已清除。",
    "provider.switch_unavailable": "当前无法切换供应商。",
    "provider.switch_running": "任务运行期间不能切换供应商。",
    "provider.default_save_failed": "本次运行已切换供应商，但无法保存默认项：{error}",
    "effort.unavailable": "当前无法控制思考强度。",
    "effort.switch_running": "任务运行期间不能切换思考强度。",
    "effort.invalid": "未知强度 {value!r}。可选值：{levels}。",
    "effort.already_selected": "思考强度已经是 {glyph} {effort}。",
    "effort.changed": "思考强度已切换为 {glyph} {effort}；从下一次模型步骤开始生效。",
    "effort.already_selected_ultracode": "思考强度已经是 {requested}。",
    "effort.changed_ultracode": "思考强度已切换为 {requested}；从下一次模型步骤开始生效。",
    "effort.save_failed": "本次运行的强度已切换，但无法保存该偏好：{error}",
    "mode.current": "当前模式：{mode}。可选模式：{modes}。",
    "mode.invalid": "未知模式 {value!r}。可选值：{modes}。",
    "mode.unavailable": "当前无法控制交互模式。",
    "mode.switch_running": "任务运行期间不能切换模式。",
    "mode.already_selected": "交互模式已经是 {glyph} {mode}。",
    "mode.changed": "交互模式已切换为 {glyph} {mode}。",
    "mode.changed_auto_limited": "已选择 Auto 安全预览：读取和编辑自动运行，命令及网络操作仍需授权；安全分类器尚未实现。",
    "mode.save_failed": "本次运行的模式已切换，但无法保存该偏好：{error}",
    "mode.limited": "受限",
    "plan.none": "此会话尚未保存结构化计划。",
    "plan.heading": "已更新计划：",
    "plan.purpose": "目标：{explanation}",
    "plan.step": "{index}. [{status}] {step}",
    "plan.comment": "   ↳ 评论：{content}",
    "plan.comment_unavailable": "当前界面无法使用计划评论。",
    "plan.comment_usage": "用法：/comment-plan 步骤序号 评论内容",
    "plan.comment_step_invalid": "计划步骤 {index} 不存在。",
    "plan.comment_added": "已保存计划步骤 {index} 的评论。",
    "plan.status.pending": "待处理",
    "plan.status.in_progress": "进行中",
    "plan.status.completed": "已完成",
    "plan.execution_unavailable": "当前界面无法执行计划。",
    "plan.execution_user": "执行当前结构化计划。",
    "plan.execution_requested": "已在接受编辑模式下从当前结构化计划开始执行。",
    "plan.scheduled": "已排队计划任务 {task_id}。准备好后运行 /run-task {task_id}。",
    "plan.task_execution_user": "运行已排队的计划任务 {task_id}。",
    "provider.already_selected": "供应商配置 {profile} 已经处于选中状态。",
    "provider.switched": "供应商配置已切换到 {profile}（{provider}/{model}）。{stopped}",
    "provider.switched_saved": "供应商配置已切换到 {profile}（{provider}/{model}）。之前的会话 {session_id} 仍已保存；下一条提示将开始新对话。{stopped}",
    "tasks.stopped_one": " 已停止上一会话中的 1 个后台任务。",
    "tasks.stopped_many": " 已停止上一会话中的 {count} 个后台任务。",
    "session.resume_unavailable": "当前无法交互式恢复会话。",
    "session.resume_running": "任务运行期间不能恢复其他会话。",
    "session.none": "当前工作区没有会话。",
    "session.none_matching": "当前工作区没有匹配 {query!r} 的会话。",
    "session.rename_unavailable": "当前无法交互式重命名会话。",
    "session.rename_running": "任务运行期间不能重命名会话。",
    "session.renamed": "会话 {session_id} 已重命名为 {title!r}。",
    "session.already_open": "会话 {session_id} 已经打开。",
    "session.profile": "配置 {profile}",
    "session.profile_unavailable": "配置 {profile}；源配置 {source} 尚未在本地就绪",
    "session.previous_saved": " 之前的会话 {session_id} 仍已保存。",
    "session.resumed": "已恢复会话 {session_id}，使用{profile_note}（{provider}/{model}）。{previous}{stopped}",
    "tasks.unavailable": "当前无法查看任务。",
    "tasks.none": "当前会话没有任务。",
    "tasks.heading": "任务：\n{lines}",
    "tasks.omitted": "……已省略 {count} 个较早任务",
    "tasks.summary": "{task_id} · {status}{exit_note} · 输出 {bytes} 字节{truncated} · 开始于 {started}",
    "tasks.exit": " · 退出码 {code}",
    "tasks.truncated": "（预览已截断）",
    "tasks.status.running": "运行中",
    "tasks.status.queued": "已排队",
    "tasks.status.completed": "已完成",
    "tasks.status.failed": "失败",
    "tasks.status.timed_out": "已超时",
    "tasks.status.cancelled": "已取消",
    "tasks.kind.plan_execution": "计划执行",
    "tasks.kind.subagent": "子代理",
    "tasks.session.summary": "{task_id} · {kind} · {status} · 开始于 {started}{finished}{plan}",
    "tasks.session.finished": " · 完成于 {finished}",
    "tasks.session.plan_revision": " · 计划修订 {fingerprint} · 已完成 {completed}/{total}",
    "tasks.view.usage": "用法：/view-task TASK_ID",
    "tasks.view.not_found": "当前会话中不存在持久任务 {task_id!r}。",
    "tasks.view.no_plan": "任务 {task_id!r} 没有已保存的计划快照。",
    "tasks.view.heading": "计划执行任务 {task_id}",
    "tasks.view.lifecycle": "{kind} · {status} · 开始于 {started}{finished}",
    "tasks.view.revision": "计划修订 {fingerprint}",
    "tasks.view.snapshot": "已保存的计划快照（仅供参考）：",
    "tasks.view.purpose": "目的：{explanation}",
    "tasks.view.step": "{index}. [{status}] {step}",
    "tasks.view.reference": "这份历史计划是只读参考；它不会更改当前计划或执行工作。",
    "tasks.run.usage": "用法：/run-task TASK_ID",
    "tasks.run.not_found": "当前会话中不存在持久任务 {task_id!r}。",
    "tasks.run.not_plan": "任务 {task_id!r} 不是计划执行任务。",
    "tasks.run.not_queued": "任务 {task_id!r} 未排队；只有已排队任务可以启动。",
    "tasks.completion.completed": "后台任务 {task_id} 已完成{exit_note}。",
    "tasks.completion.failed": "后台任务 {task_id} 失败{exit_note}。",
    "tasks.completion.timed_out": "后台任务 {task_id} 已超时{exit_note}。",
    "tasks.completion.cancelled": "后台任务 {task_id} 已取消{exit_note}。",
    "tasks.completion.exit": "（退出码 {code}）",
    "background_wake.current": "本次 TUI 会话的后台任务自动唤醒为{policy}。",
    "background_wake.invalid": "未知自动唤醒策略 {value!r}；请使用 on 或 off。",
    "background_wake.already_selected": "后台任务自动唤醒已经是{policy}。",
    "background_wake.changed": "本次 TUI 会话的后台任务自动唤醒已切换为{policy}。",
    "background_wake.policy.enabled": "已启用",
    "background_wake.policy.disabled": "已禁用",
    "background_wake.started": "后台任务已完成；正在唤醒模型一次。",
    "restore.result": "已恢复工具 {name} 的结果。",
    "restore.request": "已恢复工具请求：{names}。",
    "restore.truncated": "……[恢复的消息已截断]",
    "settings.changed": "界面语言已切换为{language}。",
    "settings.save_failed": "本次会话的语言已切换，但无法保存该偏好：{error}",
}

if _ENGLISH.keys() != _CHINESE.keys():
    raise RuntimeError("TUI translation catalogs must contain identical keys")

_CATALOGS: Final[Mapping[UiLanguage, Mapping[str, str]]] = {
    UiLanguage.ENGLISH: _ENGLISH,
    UiLanguage.SIMPLIFIED_CHINESE: _CHINESE,
}


def ui_text(locale: UiLanguage, key: str, **values: object) -> str:
    """Render one owned UI string while leaving conversation content untouched.

    渲染一个由本模块管理的 UI 字符串,同时保持会话内容不变."""

    template = _CATALOGS[locale][key]
    return template.format_map(values)


def language_name(language: UiLanguage, *, in_language: UiLanguage) -> str:
    names = {
        UiLanguage.ENGLISH: {
            UiLanguage.ENGLISH: "English",
            UiLanguage.SIMPLIFIED_CHINESE: "Simplified Chinese",
        },
        UiLanguage.SIMPLIFIED_CHINESE: {
            UiLanguage.ENGLISH: "英语",
            UiLanguage.SIMPLIFIED_CHINESE: "简体中文",
        },
    }
    return names[in_language][language]


__all__ = ["language_name", "ui_text"]
