"""Canonical execution domain package.

The package keeps ``neuro_code.domain.execution`` as the public compatibility
entry point while assigning each value-object family to a focused module.

定义规范的执行领域包. 公共兼容入口仍为 `neuro_code.domain.execution`,各值对象分布在专用模块中.
"""

from neuro_code.domain.execution.checkpoints import (
    ExecutionSegmentCheckpoint,
    ExecutionSnapshot,
    SessionExecutionRecord,
)
from neuro_code.domain.execution.outcomes import (
    AgentExecutionOutcome,
    AgentExecutionStatus,
    BudgetLimitDetail,
    ProgressKind,
    SupervisorDecision,
    SupervisorDecisionKind,
    SupervisorReasonCode,
)
from neuro_code.domain.execution.recovery import (
    MAX_RECOVERY_ID_BYTES,
    MAX_RECOVERY_REASON_BYTES,
    MAX_TURN_INPUT_BYTES,
    TurnInput,
    TurnRecoveryAttempt,
    TurnRecoveryFact,
    TurnRecoveryFactKind,
    TurnRecoveryResolution,
    TurnRecoveryStage,
    TurnRecoveryStatus,
)
from neuro_code.domain.execution.tasks import (
    ExecutionBudget,
    ExecutionBudgetPressure,
    ExecutionBudgetUsage,
    ExecutionCounters,
    SupervisionThresholds,
    ToolCallBudget,
    ToolCallCount,
    ToolInteractionFingerprint,
    TurnCancellationPolicy,
    TurnSource,
)
from neuro_code.domain.execution.verification_requirements import (
    MAX_REQUIREMENT_CRITERION_BYTES,
    MAX_REQUIREMENT_ID_BYTES,
    MAX_REQUIREMENT_ORIGIN_ID_BYTES,
    MAX_REQUIREMENT_PROVENANCE_ITEMS,
    MAX_REQUIREMENT_SCOPE_BYTES,
    MAX_REQUIREMENT_SCOPE_ITEMS,
    MAX_REQUIREMENT_SNAPSHOT_BYTES,
    MAX_VERIFICATION_REQUIREMENTS,
    RequirementActivation,
    RequirementProvenance,
    RequirementSource,
    RequirementStrength,
    VerificationRequirement,
    VerificationRequirementsSnapshot,
    canonical_requirement_id,
    canonical_requirement_payload,
    is_requirement_id,
    require_requirement_id,
)

__all__ = [
    "MAX_RECOVERY_ID_BYTES",
    "MAX_RECOVERY_REASON_BYTES",
    "MAX_REQUIREMENT_CRITERION_BYTES",
    "MAX_REQUIREMENT_ID_BYTES",
    "MAX_REQUIREMENT_ORIGIN_ID_BYTES",
    "MAX_REQUIREMENT_PROVENANCE_ITEMS",
    "MAX_REQUIREMENT_SCOPE_BYTES",
    "MAX_REQUIREMENT_SCOPE_ITEMS",
    "MAX_REQUIREMENT_SNAPSHOT_BYTES",
    "MAX_TURN_INPUT_BYTES",
    "MAX_VERIFICATION_REQUIREMENTS",
    "AgentExecutionOutcome",
    "AgentExecutionStatus",
    "BudgetLimitDetail",
    "ExecutionBudget",
    "ExecutionBudgetPressure",
    "ExecutionBudgetUsage",
    "ExecutionCounters",
    "ExecutionSegmentCheckpoint",
    "ExecutionSnapshot",
    "ProgressKind",
    "RequirementActivation",
    "RequirementProvenance",
    "RequirementSource",
    "RequirementStrength",
    "SessionExecutionRecord",
    "SupervisionThresholds",
    "SupervisorDecision",
    "SupervisorDecisionKind",
    "SupervisorReasonCode",
    "ToolCallBudget",
    "ToolCallCount",
    "ToolInteractionFingerprint",
    "TurnCancellationPolicy",
    "TurnInput",
    "TurnRecoveryAttempt",
    "TurnRecoveryFact",
    "TurnRecoveryFactKind",
    "TurnRecoveryResolution",
    "TurnRecoveryStage",
    "TurnRecoveryStatus",
    "TurnSource",
    "VerificationRequirement",
    "VerificationRequirementsSnapshot",
    "canonical_requirement_id",
    "canonical_requirement_payload",
    "is_requirement_id",
    "require_requirement_id",
]
