# ruff: noqa: RUF001
"""Deterministic, provider-free TUI visual fixtures with natural CJK punctuation."""

from __future__ import annotations

from itertools import count
from pathlib import Path
from unittest.mock import patch
from uuid import UUID

from tests.visual.markdown_fixtures import READING_FIXTURES
from tests.visual.syntax_fixtures import SYNTAX_FIXTURES

from neuro_code.application.permissions.contracts import PermissionRequest
from neuro_code.application.trace.collector import TraceCollector
from neuro_code.domain.conversation.events import AgentEvent, AgentEventKind
from neuro_code.domain.conversation.messages import Message, Role
from neuro_code.interfaces.tui.app import NeuroCodeApp
from neuro_code.interfaces.tui.screens import (
    PermissionApprovalScreen,
    SettingsScreen,
    SyntaxThemeSettingsScreen,
    TraceScreen,
)
from neuro_code.interfaces.tui.state import ToolActivityGroupState, ToolFeedbackState
from neuro_code.interfaces.tui.terminal_palette import TerminalPalette
from neuro_code.interfaces.tui.widgets import PromptInput
from neuro_code.shared.syntax_theme import SyntaxTheme
from neuro_code.shared.ui_language import UiLanguage
from neuro_code.shared.ui_theme import UiTheme

VISUAL_FIXTURES = (
    "empty-conversation",
    "empty-first-message",
    "empty-restored-history",
    "user-assistant",
    "long-markdown",
    "mixed-language-long-answer",
    "tool-activity",
    "error",
    "permission",
    "single-line-composer",
    "idle-composer",
    "multiline-composer",
    "long-composer",
    "settings",
    "trace",
    *SYNTAX_FIXTURES,
    *READING_FIXTURES,
    "syntax-settings",
)

_LONG_MARKDOWN = """# Review summary

The fixture exercises a compact reading hierarchy with **emphasis**, `inline code`,
and a short explanation that wraps at the selected terminal width. The stable baseline
should make changes to line flow and code treatment visible without relying on a live
repository or a real model response.

## Evidence

- `src/neuro_code/interfaces/tui/app.py` owns the main shell.
- Settings and trace are separate modal surfaces.
- Tool activity is grouped into a bounded presentation block.

| Surface | Fixture purpose |
| --- | --- |
| Conversation | Reading axis and message spacing |
| Code | Isolated syntax palette |
| Composer | Bounded adaptive footer and multiline input |

```python
def stable_visual_state(width: int, height: int) -> tuple[int, int]:
    return width, height
```

The final paragraph gives the long-message viewport a repeatable continuation and
exercises the same Markdown renderer used for ordinary assistant messages.
"""

_MIXED_LANGUAGE_LONG_ANSWER = """# 仓库审查结论

本轮检查了 `src/neuro_code/interfaces/tui/theme.py` 与 `tests/visual/showcases.py`。
当前**主要结论**是：正文应保持连续可读，路径和命令只作为定位证据。
This paragraph mixes English terms with 中文说明，用于观察换行与 regular 字重。

## 证据与判断

- `theme.py` 定义语义样式，`uv run pytest tests/test_tui_visual_snapshots.py -q`
  负责检查渲染结果；命令本身不是高优先级状态。
- 工具摘要应让 `read_file`、耗时 `120ms` 和路径退到次要阅读层。

> 提醒：Snapshot 固定了 Textual 的输出，但 System Theme 在真实终端上的 ANSI
> palette 仍需要人工检查。这里的引文只作为辅助说明。

### 下一步

确认列表、引用和行内 `AGENTS.md` 不形成视觉标签。围栏代码仍可保留独立背景。

最后继续阅读这一段较长的中文说明，以确认在 80 列和 120 列终端中，
段落之间的层级稳定，普通句子不会被标题、状态色或耗时数字抢走注意力。
"""


class _VisualFixtureRunner:
    """Minimal runner that cannot make provider or persistence calls."""

    session_id: None = None


def make_trace_fixture() -> TraceCollector:
    """Build a small trace with stable span IDs and bounded timing values."""

    ticks = count()

    def clock() -> float:
        return 100.0 + next(ticks) / 10

    trace_ids = count(1)

    def stable_uuid() -> UUID:
        return UUID(int=next(trace_ids))

    collector = TraceCollector(clock=clock)
    # Trace IDs are generated by the production collector. Pin only that source
    # while constructing this fixture; no process or app behavior is patched.
    with patch("neuro_code.application.trace.collector.uuid.uuid4", side_effect=stable_uuid):
        collector.begin_turn(turn_id="visual-fixture-turn", source="user")
        collector.observe(AgentEvent.create(1, AgentEventKind.MODEL_STEP_STARTED, {"step": 1}))
        collector.observe(
            AgentEvent.create(
                2,
                AgentEventKind.MODEL_REQUEST_SNAPSHOT,
                {
                    "request_id": "visual-request-01",
                    "provider": "fixture-provider",
                    "model": "fixture-model",
                    "message_count": 3,
                    "tool_count": 0,
                },
            )
        )
        collector.end_turn("succeeded")
    return collector


def make_app(
    theme: UiTheme,
    *,
    fixture: str,
    terminal_palette: TerminalPalette | None = None,
    syntax_choice: SyntaxTheme = SyntaxTheme.AUTO,
) -> NeuroCodeApp:
    trace = make_trace_fixture() if fixture == "trace" else TraceCollector()
    return NeuroCodeApp(
        _VisualFixtureRunner(),  # type: ignore[arg-type]
        trace_collector=trace,
        language=UiLanguage.ENGLISH,
        ui_theme=theme,
        syntax_theme=syntax_choice,
        terminal_palette=terminal_palette,
        provider_name="fixture-provider",
        model_name="fixture-model",
        cwd=Path("/workspace/neuro-code"),
    )


def populate_fixture(app: NeuroCodeApp, fixture: str) -> None:
    """Add deterministic presentation state after the app has mounted."""

    if fixture in READING_FIXTURES:
        app._write_entry("user", "请审查下面的内容 / Review the following evidence.")
        app._write_entry("assistant", READING_FIXTURES[fixture])
        return
    if fixture in SYNTAX_FIXTURES:
        app._write_entry("assistant", SYNTAX_FIXTURES[fixture])
        return
    if fixture in {"empty-conversation", "syntax-settings"}:
        return
    if fixture == "empty-first-message":
        app._write_entry("user", "Review this repository. / 请审查这个项目。")
        return
    if fixture == "empty-restored-history":
        app._replace_transcript(
            (
                Message(Role.USER, "请继续之前的审查。"),
                Message(Role.ASSISTANT, "Restored conversation evidence is visible."),
            )
        )
        return
    if fixture == "user-assistant":
        app._write_entry("user", "Summarize the current review findings.")
        app._write_entry(
            "assistant",
            "The review is ready. **Two** independent findings are documented below.",
        )
        return
    if fixture == "long-markdown":
        app._write_entry("user", "Show the formatted review notes.")
        app._write_entry("assistant", _LONG_MARKDOWN)
        return
    if fixture == "mixed-language-long-answer":
        app._write_entry("user", "请总结审查证据，并说明如何验证。")
        app._write_entry("assistant", _MIXED_LANGUAGE_LONG_ANSWER)
        return
    if fixture == "tool-activity":
        _populate_tool_activity(app)
        return
    if fixture == "error":
        app._write_entry("user", "Run the focused verification.")
        app._write_entry(
            "error",
            "Provider request failed: the configured endpoint returned an unavailable response.",
        )
        return
    if fixture == "multiline-composer":
        prompt = app.query_one("#prompt")
        prompt.text = "Inspect the transcript rendering\nthen compare the compact viewport."
        return
    if fixture in {"single-line-composer", "idle-composer"}:
        app.query_one("#prompt", PromptInput).text = "Review the current shell layout."
        return
    if fixture == "long-composer":
        prompt = app.query_one("#prompt", PromptInput)
        lines = [f"Evidence item {number}: inspect the current layout." for number in range(1, 13)]
        prompt.text = "\n".join(lines)
        prompt.move_cursor((len(lines) - 1, len(lines[-1])))
        return
    if fixture in {"permission", "settings", "trace"}:
        return
    raise ValueError(f"unknown visual fixture: {fixture}")


def show_fixture_screen(app: NeuroCodeApp, fixture: str, theme: UiTheme) -> None:
    """Open one stable modal fixture without invoking its side-effect handlers."""

    if fixture == "permission":
        app.push_screen(
            PermissionApprovalScreen(
                PermissionRequest(
                    call_id="visual-permission-01",
                    tool_name="bash",
                    summary="Run the focused test suite",
                    reason="This starts a local test process in the fixture workspace.",
                    scope_key="workspace",
                    intent="Run a read-only test command.",
                ),
                language=UiLanguage.ENGLISH,
            )
        )
    elif fixture == "settings":
        app.push_screen(
            SettingsScreen(
                UiLanguage.ENGLISH,
                language=UiLanguage.ENGLISH,
                provider_settings_available=False,
                ui_theme=theme,
            )
        )
    elif fixture == "trace":
        app.push_screen(TraceScreen(app._trace_collector, language=UiLanguage.ENGLISH))
    elif fixture == "syntax-settings":
        app.push_screen(
            SyntaxThemeSettingsScreen(
                app._syntax_theme,
                language=UiLanguage.ENGLISH,
                preview=app._apply_syntax_theme,
            )
        )
    elif fixture not in VISUAL_FIXTURES:
        raise ValueError(f"unknown visual fixture: {fixture}")


def _populate_tool_activity(app: NeuroCodeApp) -> None:
    group = ToolActivityGroupState()
    calls = (
        ToolFeedbackState(
            call_id="visual-read-01",
            name="read_file",
            arguments={"path": "src/neuro_code/interfaces/tui/app.py"},
            entry_index=0,
            phase="completed",
            duration="120ms",
            duration_seconds=0.12,
            content="Read 42 lines.",
        ),
        ToolFeedbackState(
            call_id="visual-search-01",
            name="grep_many",
            arguments={"pattern": "visual snapshot", "path": "tests"},
            entry_index=1,
            phase="completed",
            duration="80ms",
            duration_seconds=0.08,
            content="Found 3 matching lines.",
        ),
    )
    group.tools.extend(calls)
    app._tool_activity_groups.append(group)
    for call in calls:
        app._tool_feedback_by_entry[call.entry_index] = call
        app._tool_activity_group_by_entry[call.entry_index] = group
        app._write_entry("tool", app._tool_summary_line(call), tool_state=call)
