"""Canonical conversation and model-stream domain contracts.

定义规范的会话和模型流领域契约."""

from neuro_code.domain.conversation.compaction import (
    COMPACTION_SOURCE_FINGERPRINT_BYTES,
    MAX_DURABLE_COMPACTION_ID_BYTES,
    MAX_DURABLE_COMPACTION_SUMMARY_BYTES,
    DurableCompactionItem,
    compute_compaction_source_fingerprint,
)
from neuro_code.domain.conversation.context import (
    UPSTREAM_IMPORT_PROVIDER,
    ModelContext,
    estimate_context_tokens,
    estimate_text_tokens,
)
from neuro_code.domain.conversation.events import (
    AgentEvent,
    AgentEventKind,
    ModelBackendToolCompleted,
    ModelBackendToolStarted,
    ModelCompleted,
    ModelEvent,
    ModelInputTokenSemantics,
    ModelProviderAttemptFailed,
    ModelProviderSelected,
    ModelReasoningDelta,
    ModelRequestTrajectoryObserved,
    ModelTextDelta,
    ModelToolCall,
    ModelUsage,
)
from neuro_code.domain.conversation.interaction_mode import (
    InteractionMode,
    interaction_mode_guidance,
)
from neuro_code.domain.conversation.messages import (
    AUDIO_MODEL_PLACEHOLDER,
    BLOB_MODEL_PLACEHOLDER,
    IMAGE_MODEL_PLACEHOLDER,
    ContentPart,
    ContentPartKind,
    ContextItemKind,
    Message,
    PreservedContextItem,
    Role,
    SessionItem,
    SyntheticReason,
    ToolCall,
)
from neuro_code.domain.conversation.prompt_continuity import (
    CacheBoundaryReason,
    ModelRequestSource,
)
from neuro_code.domain.conversation.reasoning import ReasoningEffort, reasoning_guidance
from neuro_code.domain.conversation.request import (
    MAX_REQUEST_SNAPSHOT_ID_BYTES,
    REQUEST_SNAPSHOT_SCHEMA_VERSION,
    ModelRequestSnapshot,
    ModelRequestTokenEstimate,
    RequestContextFingerprints,
    build_model_request_payload,
    context_fingerprints,
    estimate_model_request_tokens,
)

__all__ = [
    "AUDIO_MODEL_PLACEHOLDER",
    "BLOB_MODEL_PLACEHOLDER",
    "COMPACTION_SOURCE_FINGERPRINT_BYTES",
    "IMAGE_MODEL_PLACEHOLDER",
    "MAX_DURABLE_COMPACTION_ID_BYTES",
    "MAX_DURABLE_COMPACTION_SUMMARY_BYTES",
    "MAX_REQUEST_SNAPSHOT_ID_BYTES",
    "REQUEST_SNAPSHOT_SCHEMA_VERSION",
    "UPSTREAM_IMPORT_PROVIDER",
    "AgentEvent",
    "AgentEventKind",
    "CacheBoundaryReason",
    "ContentPart",
    "ContentPartKind",
    "ContextItemKind",
    "DurableCompactionItem",
    "InteractionMode",
    "Message",
    "ModelBackendToolCompleted",
    "ModelBackendToolStarted",
    "ModelCompleted",
    "ModelContext",
    "ModelEvent",
    "ModelInputTokenSemantics",
    "ModelProviderAttemptFailed",
    "ModelProviderSelected",
    "ModelReasoningDelta",
    "ModelRequestSnapshot",
    "ModelRequestSource",
    "ModelRequestTokenEstimate",
    "ModelRequestTrajectoryObserved",
    "ModelTextDelta",
    "ModelToolCall",
    "ModelUsage",
    "PreservedContextItem",
    "ReasoningEffort",
    "RequestContextFingerprints",
    "Role",
    "SessionItem",
    "SyntheticReason",
    "ToolCall",
    "build_model_request_payload",
    "compute_compaction_source_fingerprint",
    "context_fingerprints",
    "estimate_context_tokens",
    "estimate_model_request_tokens",
    "estimate_text_tokens",
    "interaction_mode_guidance",
    "reasoning_guidance",
]
